///|
pub const PI : Double = 3.141592653589793

///|
pub fn ceil(x : Double) -> Double {
  @math.ceil(x)
}

///|
pub fn floor(x : Double) -> Double {
  @math.floor(x)
}

///|
pub fn round(x : Double) -> Double {
  @math.round(x)
}

///|
pub fn trunc(x : Double) -> Double {
  @math.trunc(x)
}

///|
pub fn exp(x : Double) -> Double {
  @math.exp(x)
}

///|
pub fn pow(x : Double, y : Double) -> Double {
  @math.pow(x, y)
}

///|
pub fn ln(x : Double) -> Double {
  @math.ln(x)
}

///|
pub fn sin(x : Double) -> Double {
  @math.sin(x)
}

///|
pub fn cos(x : Double) -> Double {
  @math.cos(x)
}

///|
pub fn tan(x : Double) -> Double {
  @math.tan(x)
}

///|
pub fn asin(x : Double) -> Double {
  @math.asin(x)
}

///|
pub fn acos(x : Double) -> Double {
  @math.acos(x)
}

///|
pub fn atan(x : Double) -> Double {
  @math.atan(x)
}

///|
pub fn atan2(y : Double, x : Double) -> Double {
  @math.atan2(y, x)
}

///|
pub fn sinh(x : Double) -> Double {
  @math.sinh(x)
}

///|
pub fn cosh(x : Double) -> Double {
  @math.cosh(x)
}

///|
pub fn tanh(x : Double) -> Double {
  @math.tanh(x)
}

///|
pub fn asinh(x : Double) -> Double {
  @math.asinh(x)
}

///|
pub fn acosh(x : Double) -> Double {
  @math.acosh(x)
}

///|
pub fn atanh(x : Double) -> Double {
  @math.atanh(x)
}

///|
pub fn hypot(x : Double, y : Double) -> Double {
  @math.hypot(x, y)
}
